## 1.Import required Libraries

In [90]:
import  pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.feature_selection import SelectFromModel,RFE
from sklearn.metrics import accuracy_score,recall_score,precision_score,confusion_matrix

## 2.Import Dataset

In [82]:
breast_cancer_data = load_breast_cancer()
breast_cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [6]:
breast_cancer_df = pd.DataFrame(breast_cancer_data.data,columns=breast_cancer_data.feature_names)
breast_cancer_df

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [8]:
breast_cancer_df["Target"] = breast_cancer_data.target
breast_cancer_df

     mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension  Target
0          17.99         10.38          122.80  ...          0.4601                  0.11890       0
1          20.57         17.77          132.90  ...          0.2750                  0.08902       0
2          19.69         21.25          130.00  ...          0.3613                  0.08758       0
3          11.42         20.38           77.58  ...          0.6638                  0.17300       0
4          20.29         14.34          135.10  ...          0.2364                  0.07678       0
..           ...           ...             ...  ...             ...                      ...     ...
564        21.56         22.39          142.00  ...          0.2060                  0.07115       0
565        20.13         28.25          131.20  ...          0.2572                  0.06637       0
566        16.60         28.08          108.30  ...          0.2218                  0.07820       0
567        20.60         29.33          140.10  ...          0.4087                  0.12400       0
568         7.76         24.54           47.92  ...          0.2871                  0.07039       1

[569 rows x 31 columns]

## 3.Data Understanding

In [9]:
breast_cancer_df.shape

(569, 31)

In [10]:
breast_cancer_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int64
dtype: object

In [11]:
breast_cancer_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

## 4.Data Preparation

In [13]:
X=breast_cancer_df.drop("Target",axis=1)
y=breast_cancer_df["Target"]

X.shape,y.shape

((569, 30), (569,))

## 5.Model Building

In [15]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.20,random_state=123,shuffle=True)
X_train.shape,X_test.shape

((455, 30), (114, 30))

In [27]:
rf_classifier = RandomForestClassifier(max_depth = 7)
rf_classifier.fit(X_train,y_train)

y_pred = rf_classifier.predict(X_train)

print("Accuracy Score:",round(accuracy_score(y_train,y_pred),4))
print("Precision Score:",round(precision_score(y_train,y_pred),4))
print("Recall Score:",round(recall_score(y_train,y_pred),4))
print("Confusion Matrix:\n",confusion_matrix(y_train,y_pred))

Accuracy Score: 1.0
Precision Score: 1.0
Recall Score: 1.0
Confusion Matrix:
 [[171   0]
 [  0 284]]

In [28]:
rf_classifier.feature_importances_

array([0.03790803, 0.01200581, 0.0478678 , 0.06542931, 0.00473155,
       0.01851618, 0.03294059, 0.09993298, 0.00461195, 0.00233633,
       0.00640756, 0.00443363, 0.01406846, 0.036075  , 0.0043478 ,
       0.00533034, 0.00358179, 0.0066147 , 0.0036904 , 0.0058991 ,
       0.10484134, 0.01993515, 0.12948956, 0.12338302, 0.01464041,
       0.01660879, 0.02526973, 0.12891287, 0.01230927, 0.00788057])

## Feature Engineering

In [31]:
select_from_model = SelectFromModel(estimator=RandomForestClassifier(),max_features=None)
select_from_model.fit(X_train,y_train)

SelectFromModel(estimator=RandomForestClassifier())

In [32]:
select_from_model.get_support()

array([ True, False, False,  True, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True,  True, False, False,  True,
        True, False, False])

In [35]:
breast_cancer_data.feature_names[select_from_model.get_support()]

array(['mean radius', 'mean area', 'mean concavity',
       'mean concave points', 'worst radius', 'worst perimeter',
       'worst area', 'worst concavity', 'worst concave points'],
      dtype='<U23')

In [91]:
len(select_from_model.get_support())

30

In [38]:
X_train_select_from_model = select_from_model.transform(X_train)
X_test_select_from_model =select_from_model.transform(X_test)

In [41]:
X_train_select_from_model.shape,X_test_select_from_model.shape

((455, 9), (114, 9))

In [43]:
def runrandomforestclassifier(X_train,X_test,y_train,y_test):
    rf_model = RandomForestClassifier(max_depth=7,random_state=123)
    rf_model.fit(X_train,y_train)

    y_pred = rf_model.predict(X_test)

    print("Accuracy Score:",round(accuracy_score(y_test,y_pred),4))
    print("Precision Score:",round(precision_score(y_test,y_pred),4))
    print("Recall Score",round(recall_score(y_test,y_pred),4))
    print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

In [46]:
%%time
runrandomforestclassifier(X_train,X_test,y_train,y_test)   # 30 features

Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
CPU times: total: 469 ms
Wall time: 479 ms

In [49]:
%%time
runrandomforestclassifier(X_train_select_from_model,X_test_select_from_model,y_train,y_test) #9 Features

Accuracy Score: 0.9649
Precision Score: 0.9726
Recall Score 0.9726
Confusion Matrix:
 [[39  2]
 [ 2 71]]
CPU times: total: 359 ms
Wall time: 408 ms

## 2nd Technique RFE

In [51]:
rfe_model = RFE(estimator = RandomForestClassifier(),n_features_to_select=12)
rfe_model.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=12)

In [53]:
rfe_model.get_support()

array([ True, False,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True,  True, False, False,
        True, False, False])

In [55]:
len(breast_cancer_data.feature_names[rfe_model.get_support()])

12

In [56]:
X_train_rfe_model = rfe_model.transform(X_train)
X_test_rfe_model = rfe_model.transform(X_test)

In [57]:
X_train_rfe_model.shape,X_test_rfe_model.shape

((455, 12), (114, 12))

In [62]:
%%time
runrandomforestclassifier(X_train,X_test,y_train,y_test) #30 Features

Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
CPU times: total: 391 ms
Wall time: 426 ms

In [63]:
%%time
runrandomforestclassifier(X_train_rfe_model,X_test_rfe_model,y_train,y_test) #12 Features

Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
CPU times: total: 375 ms
Wall time: 368 ms

## 3.Take the important features from Gradient Boosting and train it with Random Forest Algorithm

In [65]:
rfe_model= RFE(estimator=GradientBoostingClassifier(),n_features_to_select=12)
rfe_model.fit(X_train,y_train)

RFE(estimator=GradientBoostingClassifier(), n_features_to_select=12)

In [66]:
rfe_model.get_support()

array([False,  True, False, False, False, False,  True,  True, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False,  True,  True,  True,  True, False, False,  True,
        True, False, False])

In [68]:
%%time
runrandomforestclassifier(X_train_rfe_model,X_test_rfe_model,y_train,y_test) #12 Features

Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
CPU times: total: 375 ms
Wall time: 390 ms

In [69]:
X_train_rfe_model = rfe_model.transform(X_train)
X_test_rfe_model = rfe_model.transform(X_test)

In [70]:
X_train_rfe_model.shape,X_test_rfe_model.shape

((455, 12), (114, 12))

In [73]:
%%time
runrandomforestclassifier(X_train,X_test,y_train,y_test) #30 Features

Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
CPU times: total: 625 ms
Wall time: 922 ms

In [75]:
%%time
runrandomforestclassifier(X_train_rfe_model,X_test_rfe_model,y_train,y_test) #12 Features

Accuracy Score: 0.9737
Precision Score: 0.9605
Recall Score 1.0
Confusion Matrix:
 [[38  3]
 [ 0 73]]
CPU times: total: 375 ms
Wall time: 386 ms

## How to choose the Optimal number of Features to train my Model?

In [76]:
def runRandomForestClassifier(X_train,X_test,y_train,y_test):
    rf_model = RandomForestClassifier(max_depth=7,random_state=123)
    rf_model.fit(X_train,y_train)
    
    y_pred = rf_model.predict(X_test)
    
    print("Accuracy Score:",round(accuracy_score(y_test,y_pred),4))
    print("Precision Score:",round(precision_score(y_test,y_pred),4))
    print("Recall Score",round(recall_score(y_test,y_pred),4))
    print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

In [77]:
for i in range(1,31):
    rfe_model = RFE(estimator = GradientBoostingClassifier(),n_features_to_select=i)
    rfe_model.fit(X_train,y_train)
    X_train_rfe_model = rfe_model.transform(X_train)
    X_test_rfe_model = rfe_model.transform(X_test)
    print("Selected Features:",i)
    runRandomForestClassifier(X_train_rfe_model,X_test_rfe_model,y_train,y_test)
    print("**************************")

Selected Features: 1
Accuracy Score: 0.9035
Precision Score: 0.9189
Recall Score 0.9315
Confusion Matrix:
 [[35  6]
 [ 5 68]]
**************************
Selected Features: 2
Accuracy Score: 0.9649
Precision Score: 0.9726
Recall Score 0.9726
Confusion Matrix:
 [[39  2]
 [ 2 71]]
**************************
Selected Features: 3
Accuracy Score: 0.9737
Precision Score: 0.9605
Recall Score 1.0
Confusion Matrix:
 [[38  3]
 [ 0 73]]
**************************
Selected Features: 4
Accuracy Score: 0.9649
Precision Score: 0.96
Recall Score 0.9863
Confusion Matrix:
 [[38  3]
 [ 1 72]]
**************************
Selected Features: 5
Accuracy Score: 0.9737
Precision Score: 0.9605
Recall Score 1.0
Confusion Matrix:
 [[38  3]
 [ 0 73]]
**************************
Selected Features: 6
Accuracy Score: 0.9825
Precision Score: 0.9863
Recall Score 0.9863
Confusion Matrix:
 [[40  1]
 [ 1 72]]
**************************
Selected Features: 7
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 8
Accuracy Score: 0.9825
Precision Score: 0.9733
Recall Score 1.0
Confusion Matrix:
 [[39  2]
 [ 0 73]]
**************************
Selected Features: 9
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 10
Accuracy Score: 0.9825
Precision Score: 0.9733
Recall Score 1.0
Confusion Matrix:
 [[39  2]
 [ 0 73]]
**************************
Selected Features: 11
Accuracy Score: 0.9825
Precision Score: 0.9733
Recall Score 1.0
Confusion Matrix:
 [[39  2]
 [ 0 73]]
**************************
Selected Features: 12
Accuracy Score: 0.9737
Precision Score: 0.9605
Recall Score 1.0
Confusion Matrix:
 [[38  3]
 [ 0 73]]
**************************
Selected Features: 13
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 14
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 15
Accuracy Score: 0.9825
Precision Score: 0.9733
Recall Score 1.0
Confusion Matrix:
 [[39  2]
 [ 0 73]]
**************************
Selected Features: 16
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 17
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 18
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 19
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 20
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 21
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 22
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 23
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 24
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 25
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 26
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 27
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 28
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 29
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************
Selected Features: 30
Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
**************************

## We found is the Optimal Numberof features

In [78]:
rfe_model = RFE(estimator = GradientBoostingClassifier(),n_features_to_select=22)
rfe_model.fit(X_train,y_train)

RFE(estimator=GradientBoostingClassifier(), n_features_to_select=22)

In [79]:
rfe_model.get_support()

array([False,  True, False, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False])

In [84]:
breast_cancer_data.feature_names[rfe_model.get_support()]

array(['mean texture', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean fractal dimension', 'radius error',
       'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'symmetry error', 'fractal dimension error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst concavity', 'worst concave points',
       'worst symmetry'], dtype='<U23')

In [85]:
len(breast_cancer_data.feature_names[rfe_model.get_support()])

22

In [86]:
X_train_rfe_model = rfe_model.transform(X_train)
X_test_rfe_model = rfe_model.transform(X_test)

In [87]:
X_train_rfe_model.shape,X_test_rfe_model.shape

((455, 22), (114, 22))

In [88]:
%%time
runRandomForestClassifier(X_train,X_test,y_train,y_test) #30 Features

Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
CPU times: total: 453 ms
Wall time: 464 ms

In [89]:
%%time
runRandomForestClassifier(X_train_rfe_model,X_test_rfe_model,y_train,y_test) #12 Features

Accuracy Score: 0.9912
Precision Score: 0.9865
Recall Score 1.0
Confusion Matrix:
 [[40  1]
 [ 0 73]]
CPU times: total: 391 ms
Wall time: 391 ms